-- ============================================================
-- DAY 22
-- RFM CUSTOMER SEGMENTATION ANALYSIS
-- Sales Data Analysis using SQL
-- ============================================================

USE sales_analysis_db;


-- ============================================================
-- QUERY 1: Check Customers Table
-- ============================================================

SELECT *
FROM customers
LIMIT 10;


-- ============================================================
-- QUERY 2: Check Orders Table
-- ============================================================

SELECT *
FROM orders
LIMIT 10;


-- ============================================================
-- QUERY 3: Check Order Items Table
-- ============================================================

SELECT *
FROM order_items
LIMIT 10;


-- ============================================================
-- QUERY 4: Check Products Table
-- ============================================================

SELECT *
FROM products
LIMIT 10;


-- ============================================================
-- RFM ANALYSIS
-- ============================================================

-- Recency:
-- Number of days since the customer's most recent order.
--
-- Frequency:
-- Number of unique orders placed by the customer.
--
-- Monetary:
-- Total revenue generated by the customer.


-- ============================================================
-- QUERY 5: Customer RFM Base Analysis
-- ============================================================

SELECT
    c.customer_id,

    MAX(o.order_date) AS last_order_date,

    COUNT(DISTINCT o.order_id) AS frequency,

    SUM(oi.quantity * p.price) AS monetary_value

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

ORDER BY
    monetary_value DESC;


-- ============================================================
-- QUERY 6: Calculate Customer Recency
-- ============================================================

SELECT
    c.customer_id,

    MAX(o.order_date) AS last_order_date,

    DATEDIFF(
        (SELECT MAX(order_date) FROM orders),
        MAX(o.order_date)
    ) AS recency_days,

    COUNT(DISTINCT o.order_id) AS frequency,

    SUM(oi.quantity * p.price) AS monetary_value

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

ORDER BY
    recency_days ASC;


-- ============================================================
-- QUERY 7: RFM Scores
-- ============================================================

WITH rfm AS
(
    SELECT
        c.customer_id,

        DATEDIFF(
            (SELECT MAX(order_date) FROM orders),
            MAX(o.order_date)
        ) AS recency_days,

        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(oi.quantity * p.price) AS monetary_value

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
)

SELECT
    customer_id,
    recency_days,
    frequency,
    monetary_value,

    NTILE(5) OVER (
        ORDER BY recency_days DESC
    ) AS recency_score,

    NTILE(5) OVER (
        ORDER BY frequency
    ) AS frequency_score,

    NTILE(5) OVER (
        ORDER BY monetary_value
    ) AS monetary_score

FROM rfm

ORDER BY
    monetary_value DESC;


-- ============================================================
-- QUERY 8: Combined RFM Score
-- ============================================================

WITH rfm AS
(
    SELECT
        c.customer_id,

        DATEDIFF(
            (SELECT MAX(order_date) FROM orders),
            MAX(o.order_date)
        ) AS recency_days,

        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(oi.quantity * p.price) AS monetary_value

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
),

rfm_scores AS
(
    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary_value,

        NTILE(5) OVER (
            ORDER BY recency_days DESC
        ) AS recency_score,

        NTILE(5) OVER (
            ORDER BY frequency
        ) AS frequency_score,

        NTILE(5) OVER (
            ORDER BY monetary_value
        ) AS monetary_score

    FROM rfm
)

SELECT
    customer_id,
    recency_days,
    frequency,
    monetary_value,
    recency_score,
    frequency_score,
    monetary_score,

    (
        recency_score
        + frequency_score
        + monetary_score
    ) AS rfm_score

FROM rfm_scores

ORDER BY
    rfm_score DESC;


-- ============================================================
-- QUERY 9: Customer Segmentation
-- ============================================================

WITH rfm AS
(
    SELECT
        c.customer_id,

        DATEDIFF(
            (SELECT MAX(order_date) FROM orders),
            MAX(o.order_date)
        ) AS recency_days,

        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(oi.quantity * p.price) AS monetary_value

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
),

rfm_scores AS
(
    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary_value,

        NTILE(5) OVER (
            ORDER BY recency_days DESC
        ) AS recency_score,

        NTILE(5) OVER (
            ORDER BY frequency
        ) AS frequency_score,

        NTILE(5) OVER (
            ORDER BY monetary_value
        ) AS monetary_score

    FROM rfm
)

SELECT
    customer_id,
    recency_days,
    frequency,
    monetary_value,

    recency_score,
    frequency_score,
    monetary_score,

    CASE

        WHEN recency_score >= 4
             AND frequency_score >= 4
             AND monetary_score >= 4
        THEN 'Champions'

        WHEN recency_score >= 4
             AND frequency_score >= 3
        THEN 'Loyal Customers'

        WHEN recency_score >= 4
             AND frequency_score <= 2
        THEN 'New Customers'

        WHEN recency_score <= 2
             AND frequency_score >= 3
        THEN 'At Risk Customers'

        WHEN recency_score <= 2
             AND monetary_score >= 3
        THEN 'High Value At Risk'

        ELSE 'Regular Customers'

    END AS customer_segment

FROM rfm_scores

ORDER BY
    monetary_value DESC;


-- ============================================================
-- QUERY 10: Segment Summary
-- ============================================================

WITH rfm AS
(
    SELECT
        c.customer_id,

        DATEDIFF(
            (SELECT MAX(order_date) FROM orders),
            MAX(o.order_date)
        ) AS recency_days,

        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(oi.quantity * p.price) AS monetary_value

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
),

rfm_scores AS
(
    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary_value,

        NTILE(5) OVER (
            ORDER BY recency_days DESC
        ) AS recency_score,

        NTILE(5) OVER (
            ORDER BY frequency
        ) AS frequency_score,

        NTILE(5) OVER (
            ORDER BY monetary_value
        ) AS monetary_score

    FROM rfm
),

segmented_customers AS
(
    SELECT
        customer_id,
        recency_days,
        frequency,
        monetary_value,

        CASE

            WHEN recency_score >= 4
                 AND frequency_score >= 4
                 AND monetary_score >= 4
            THEN 'Champions'

            WHEN recency_score >= 4
                 AND frequency_score >= 3
            THEN 'Loyal Customers'

            WHEN recency_score >= 4
                 AND frequency_score <= 2
            THEN 'New Customers'

            WHEN recency_score <= 2
                 AND frequency_score >= 3
            THEN 'At Risk Customers'

            WHEN recency_score <= 2
                 AND monetary_score >= 3
            THEN 'High Value At Risk'

            ELSE 'Regular Customers'

        END AS customer_segment

    FROM rfm_scores
)

SELECT
    customer_segment,

    COUNT(*) AS customer_count,

    SUM(frequency) AS total_orders,

    SUM(monetary_value) AS total_revenue,

    ROUND(
        AVG(monetary_value),
        2
    ) AS average_customer_value

FROM segmented_customers

GROUP BY
    customer_segment

ORDER BY
    total_revenue DESC;


-- ============================================================
-- QUERY 11: Top Customers by Monetary Value
-- ============================================================

SELECT
    c.customer_id,

    COUNT(DISTINCT o.order_id) AS total_orders,

    SUM(oi.quantity * p.price) AS total_revenue

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

ORDER BY
    total_revenue DESC

LIMIT 10;


-- ============================================================
-- QUERY 12: Most Frequent Customers
-- ============================================================

SELECT
    c.customer_id,

    COUNT(DISTINCT o.order_id) AS total_orders,

    SUM(oi.quantity * p.price) AS total_revenue

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

ORDER BY
    total_orders DESC

LIMIT 10;


-- ============================================================
-- QUERY 13: Customer Revenue Contribution
-- ============================================================

WITH customer_revenue AS
(
    SELECT
        c.customer_id,

        SUM(oi.quantity * p.price) AS revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
)

SELECT
    customer_id,
    revenue,

    ROUND(
        revenue /
        SUM(revenue) OVER () * 100,
        2
    ) AS revenue_percentage

FROM customer_revenue

ORDER BY
    revenue DESC;


-- ============================================================
-- QUERY 14: Customer Revenue Ranking
-- ============================================================

WITH customer_revenue AS
(
    SELECT
        c.customer_id,

        SUM(oi.quantity * p.price) AS revenue

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
)

SELECT
    customer_id,
    revenue,

    RANK() OVER (
        ORDER BY revenue DESC
    ) AS revenue_rank

FROM customer_revenue

ORDER BY
    revenue_rank;


-- ============================================================
-- QUERY 15: Customer Order Frequency Ranking
-- ============================================================

WITH customer_orders AS
(
    SELECT
        c.customer_id,

        COUNT(DISTINCT o.order_id) AS total_orders

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    GROUP BY
        c.customer_id
)

SELECT
    customer_id,
    total_orders,

    DENSE_RANK() OVER (
        ORDER BY total_orders DESC
    ) AS frequency_rank

FROM customer_orders

ORDER BY
    frequency_rank;


-- ============================================================
-- QUERY 16: Customer Lifetime Value
-- ============================================================

SELECT
    c.customer_id,

    COUNT(DISTINCT o.order_id) AS total_orders,

    SUM(oi.quantity * p.price) AS lifetime_value,

    ROUND(
        SUM(oi.quantity * p.price)
        /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

ORDER BY
    lifetime_value DESC;


-- ============================================================
-- QUERY 17: Customers with High Lifetime Value
-- ============================================================

SELECT
    c.customer_id,

    SUM(oi.quantity * p.price) AS lifetime_value

FROM customers c

JOIN orders o
    ON c.customer_id = o.customer_id

JOIN order_items oi
    ON o.order_id = oi.order_id

JOIN products p
    ON oi.product_id = p.product_id

GROUP BY
    c.customer_id

HAVING
    lifetime_value >
    (
        SELECT
            AVG(customer_revenue)

        FROM
        (
            SELECT
                SUM(oi2.quantity * p2.price)
                AS customer_revenue

            FROM orders o2

            JOIN order_items oi2
                ON o2.order_id = oi2.order_id

            JOIN products p2
                ON oi2.product_id = p2.product_id

            GROUP BY
                o2.customer_id

        ) AS revenue_table
    )

ORDER BY
    lifetime_value DESC;


-- ============================================================
-- QUERY 18: Final RFM Customer Report
-- ============================================================

WITH customer_metrics AS
(
    SELECT
        c.customer_id,

        MAX(o.order_date) AS last_order_date,

        DATEDIFF(
            (SELECT MAX(order_date) FROM orders),
            MAX(o.order_date)
        ) AS recency_days,

        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(oi.quantity * p.price) AS monetary_value

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN products p
        ON oi.product_id = p.product_id

    GROUP BY
        c.customer_id
)

SELECT
    customer_id,
    last_order_date,
    recency_days,
    frequency,
    monetary_value,

    CASE

        WHEN recency_days <= 30
             AND frequency >= 5
             AND monetary_value >= 10000
        THEN 'Champions'

        WHEN recency_days <= 60
             AND frequency >= 3
        THEN 'Loyal Customers'

        WHEN recency_days <= 30
             AND frequency <= 2
        THEN 'New Customers'

        WHEN recency_days > 90
             AND frequency >= 3
        THEN 'At Risk Customers'

        WHEN recency_days > 90
             AND monetary_value >= 5000
        THEN 'High Value At Risk'

        ELSE 'Regular Customers'

    END AS customer_segment

FROM customer_metrics

ORDER BY
    monetary_value DESC;


-- ============================================================
-- END OF DAY 22
-- RFM CUSTOMER SEGMENTATION ANALYSIS
-- ============================================================