USE sales_analysis_db;


-- ============================================================
-- DAY 16: ADVANCED BUSINESS CASE STUDY
-- Sales Performance & Customer Analysis
-- ============================================================


-- ============================================================
-- 1. CUSTOMER SALES PERFORMANCE
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_quantity,
    SUM(oi.quantity * p.price) AS total_revenue,
    ROUND(
        SUM(oi.quantity * p.price) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC;


-- ============================================================
-- 2. TOP 5 CUSTOMERS BY REVENUE
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    SUM(oi.quantity * p.price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC
LIMIT 5;


-- ============================================================
-- 3. PRODUCT PERFORMANCE ANALYSIS
-- ============================================================

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold,
    SUM(oi.quantity * p.price) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC;


-- ============================================================
-- 4. TOP 5 PRODUCTS BY REVENUE
-- ============================================================

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity * p.price) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC
LIMIT 5;


-- ============================================================
-- 5. REPEAT CUSTOMERS
-- Customers with more than one order
-- ============================================================

SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.customer_name
HAVING COUNT(o.order_id) > 1
ORDER BY total_orders DESC;


-- ============================================================
-- 6. HIGH-VALUE CUSTOMERS
-- Customers spending more than average customer revenue
-- ============================================================

WITH customer_sales AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(oi.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_revenue
FROM customer_sales
WHERE total_revenue >
(
    SELECT AVG(total_revenue)
    FROM customer_sales
)
ORDER BY total_revenue DESC;


-- ============================================================
-- 7. CUSTOMER REVENUE RANKING
-- ============================================================

WITH customer_sales AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(oi.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_revenue,
    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank
FROM customer_sales
ORDER BY revenue_rank;


-- ============================================================
-- 8. CUSTOMER REVENUE CONTRIBUTION
-- Percentage of total revenue generated by each customer
-- ============================================================

WITH customer_sales AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(oi.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_revenue,
    ROUND(
        total_revenue * 100 /
        SUM(total_revenue) OVER (),
        2
    ) AS revenue_contribution_percentage
FROM customer_sales
ORDER BY revenue_contribution_percentage DESC;


-- ============================================================
-- 9. BUSINESS SUMMARY
-- ============================================================

SELECT

    (
        SELECT SUM(oi.quantity * p.price)
        FROM order_items oi
        JOIN products p
            ON oi.product_id = p.product_id
    ) AS total_revenue,

    (
        SELECT COUNT(*)
        FROM orders
    ) AS total_orders,

    (
        SELECT COUNT(*)
        FROM customers
    ) AS total_customers,

    (
        SELECT COUNT(*)
        FROM products
    ) AS total_products;


-- ============================================================
-- 10. AVERAGE CUSTOMER REVENUE
-- ============================================================

WITH customer_sales AS
(
    SELECT
        c.customer_id,
        SUM(oi.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id
)

SELECT
    ROUND(AVG(total_revenue), 2) AS average_customer_revenue
FROM customer_sales;


-- ============================================================
-- 11. BEST-SELLING PRODUCT BY QUANTITY
-- ============================================================

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 1;


-- ============================================================
-- 12. HIGHEST REVENUE PRODUCT
-- ============================================================

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity * p.price) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_revenue DESC
LIMIT 1;


-- ============================================================
-- 13. CUSTOMER ORDER CATEGORY
-- ============================================================

WITH customer_orders AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    LEFT JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_orders,

    CASE
        WHEN total_orders = 0 THEN 'No Orders'
        WHEN total_orders = 1 THEN 'One-Time Customer'
        WHEN total_orders BETWEEN 2 AND 3 THEN 'Repeat Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment

FROM customer_orders
ORDER BY total_orders DESC;


-- ============================================================
-- 14. FINAL BUSINESS REPORT
-- ============================================================

WITH customer_sales AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(oi.quantity * p.price) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_orders,
    total_revenue,

    DENSE_RANK() OVER (
        ORDER BY total_revenue DESC
    ) AS revenue_rank,

    ROUND(
        total_revenue * 100 /
        SUM(total_revenue) OVER (),
        2
    ) AS revenue_contribution_percentage,

    CASE
        WHEN total_revenue >=
             (SELECT AVG(total_revenue) FROM customer_sales)
        THEN 'High Value'
        ELSE 'Standard Value'
    END AS customer_value_segment

FROM customer_sales
ORDER BY revenue_rank;