USE sales_analysis_db;


-- ============================================================
-- DAY 49
-- SALES ORDER VALUE & BASKET ANALYSIS
-- ============================================================


-- ============================================================
-- ANALYSIS 1
-- TOTAL NUMBER OF ORDERS
-- ============================================================

SELECT
    COUNT(DISTINCT o.order_id) AS total_orders
FROM orders o;


-- ============================================================
-- ANALYSIS 2
-- TOTAL SALES REVENUE
-- ============================================================

SELECT
    ROUND(SUM(oi.quantity * p.price), 2) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id;


-- ============================================================
-- ANALYSIS 3
-- REVENUE GENERATED BY EACH ORDER
-- ============================================================

SELECT
    o.order_id,
    ROUND(SUM(oi.quantity * p.price), 2) AS order_value
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY o.order_id
ORDER BY order_value DESC;


-- ============================================================
-- ANALYSIS 4
-- AVERAGE ORDER VALUE
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    ROUND(AVG(order_value), 2) AS average_order_value
FROM order_values;


-- ============================================================
-- ANALYSIS 5
-- MINIMUM ORDER VALUE
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    ROUND(MIN(order_value), 2) AS minimum_order_value
FROM order_values;


-- ============================================================
-- ANALYSIS 6
-- MAXIMUM ORDER VALUE
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    ROUND(MAX(order_value), 2) AS maximum_order_value
FROM order_values;


-- ============================================================
-- ANALYSIS 7
-- AVERAGE UNITS PER ORDER
-- ============================================================

WITH order_units AS (
    SELECT
        o.order_id,
        SUM(oi.quantity) AS total_units
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id
)

SELECT
    ROUND(AVG(total_units), 2) AS average_units_per_order
FROM order_units;


-- ============================================================
-- ANALYSIS 8
-- MINIMUM AND MAXIMUM UNITS PER ORDER
-- ============================================================

WITH order_units AS (
    SELECT
        o.order_id,
        SUM(oi.quantity) AS total_units
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id
)

SELECT
    MIN(total_units) AS minimum_units_per_order,
    MAX(total_units) AS maximum_units_per_order
FROM order_units;


-- ============================================================
-- ANALYSIS 9
-- ORDER VALUE CLASSIFICATION
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    order_id,
    ROUND(order_value, 2) AS order_value,
    CASE
        WHEN order_value < 500 THEN 'Low Value Order'
        WHEN order_value < 2000 THEN 'Medium Value Order'
        WHEN order_value < 5000 THEN 'High Value Order'
        ELSE 'Very High Value Order'
    END AS order_value_category
FROM order_values
ORDER BY order_value DESC;


-- ============================================================
-- ANALYSIS 10
-- HIGH-VALUE ORDER ANALYSIS
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    order_id,
    ROUND(order_value, 2) AS order_value
FROM order_values
WHERE order_value >= 5000
ORDER BY order_value DESC;


-- ============================================================
-- ANALYSIS 11
-- MONTHLY ORDER VALUE ANALYSIS
-- ============================================================

SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS sales_month,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.quantity * p.price), 2) AS total_revenue,
    ROUND(
        SUM(oi.quantity * p.price)
        / COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY sales_month;


-- ============================================================
-- ANALYSIS 12
-- ORDER VALUE RANKING
-- ============================================================

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    order_id,
    ROUND(order_value, 2) AS order_value,
    RANK() OVER (
        ORDER BY order_value DESC
    ) AS order_value_rank
FROM order_values
ORDER BY order_value_rank;


-- ============================================================
-- ANALYSIS 13
-- FINAL ORDER VALUE & BASKET SUMMARY
-- ============================================================

WITH order_summary AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * p.price) AS order_value,
        SUM(oi.quantity) AS total_units
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)

SELECT
    COUNT(*) AS total_orders,
    ROUND(SUM(order_value), 2) AS total_revenue,
    ROUND(AVG(order_value), 2) AS average_order_value,
    ROUND(MIN(order_value), 2) AS minimum_order_value,
    ROUND(MAX(order_value), 2) AS maximum_order_value,
    ROUND(AVG(total_units), 2) AS average_units_per_order,
    MIN(total_units) AS minimum_units_per_order,
    MAX(total_units) AS maximum_units_per_order
FROM order_summary;